// docent-docs: renders a docs.json file (see modules/typeset/schema.zig for
// the schema it conforms to) into a document.
//
// A package can define multiple modules (library + one or more executables/
// tests); `docs.modules` holds one entry per discovered target (see
// src/cli/commands/typeset.zig), each rendered as its own top-level (level
// 1) section via `render-namespace`, which itself recurses using exactly
// two further heading levels regardless of true nesting depth -- see
// decl.typ's module doc comment.
//
// `docs.appendix` (populated via `--deps`) holds bundled `.path`
// dependencies, rendered after `modules` under an "Appendix" divider using
// the same `render-namespace` -- everything shares one Typst compilation,
// so a reference from a primary module into an appendix dependency (or vice
// versa) resolves as an ordinary internal link, not an external URL.
//
// Cross-reference links are baked into `doc` markup by serialize.zig /
// typst.zig as `#link(label("..."))`, which resolves against the
// `#label(decl.id)` decl.typ attaches to every rendered heading.
//
// Math in doc comments is emitted as MiTeX calls (`#mi` / `#mitex`); fenced
// code blocks are ordinary Typst raw blocks styled by Codly.

#import "@preview/mitex:0.2.7": *
#import "@preview/codly:1.3.0": *
#import "@preview/codly-languages:0.1.1": *
#import "decl.typ": render-namespace

#show: codly-init.with()
#codly(languages: codly-languages)

#let docs-json-path = sys.inputs.at("docs-json", default: "docs.json")
#let docs = json(docs-json-path)

#let title = docs.modules.map(m => m.name).join(", ")

#set document(title: title)
#set page(numbering: "1", margin: (x: 2.5cm, y: 2.5cm))
#set heading(numbering: "1.1.1")
#set text(size: 10.5pt, font: "IBM Plex Sans")
#show heading: set text(font: "IBM Plex Serif")
#show raw: set text(font: "IBM Plex Mono")
#set par(justify: true)

// Inline code: shaded background (Codly handles block raw / fences).
#show raw.where(block: false): it => box(
  fill: luma(240),
  outset: (y: 2pt, x: 1pt),
  radius: 2pt,
  it,
)

#show link: set text(fill: rgb("#1a56db"))

#align(center)[
  #text(size: 22pt, weight: "bold")[#title]
  #v(0.3em)
  #text(size: 10pt, fill: luma(100))[
    Generated by #docs.generator.tool_version with Zig #docs.generator.zig_version
    on #docs.generator.generated_at
  ]
]

#v(1em)
#outline(depth: 3)
#v(1em)

#for module in docs.modules [
  #render-namespace(module, level: 1)
]

#if docs.appendix.len() > 0 [
  #pagebreak(weak: true)
  #heading(level: 1, numbering: none, outlined: true)[Appendix: Bundled Dependencies]
  #v(1em)

  #for module in docs.appendix [
    #render-namespace(module, level: 1)
  ]
]
