// docent-docs: renders a docs.json file (see src/lib/typeset/schema.zig for
// the schema it conforms to) into a document.
//
// v0.3 scope: everything from v0.2 (nesting, field/param tables), plus
// cross-reference links (baked into `doc` markup by json_emit.zig /
// markdown_typst.zig as `#link(label("..."))`, which resolves against the
// `#label(decl.id)` decl.typ attaches to every rendered heading) and a
// visual design pass (code styling, table of contents).

#import "decl.typ": render-decl

#let docs-json-path = sys.inputs.at("docs-json", default: "docs.json")
#let docs = json(docs-json-path)

#set document(title: docs.root.name)
#set page(numbering: "1", margin: (x: 2.5cm, y: 2.5cm))
#set heading(numbering: "1.1")
#set text(size: 10.5pt)
#set par(justify: true)

// Inline code: shaded background, tight padding.
#show raw.where(block: false): it => box(
  fill: luma(240),
  outset: (y: 2pt, x: 1pt),
  radius: 2pt,
  it,
)

// Fenced/signature code blocks: shaded card, full width.
#show raw.where(block: true): it => block(
  fill: luma(245),
  stroke: 0.5pt + luma(210),
  inset: 8pt,
  radius: 4pt,
  width: 100%,
  it,
)

#show link: set text(fill: rgb("#1a56db"))

#align(center)[
  #text(size: 22pt, weight: "bold")[#docs.root.name]
  #v(0.3em)
  #text(size: 10pt, fill: luma(100))[
    Generated by #docs.generator.tool_version with Zig #docs.generator.zig_version
    on #docs.generator.generated_at
  ]
]

#v(1em)
#outline(depth: 3)
#v(1em)

= #docs.root.name#label(docs.root.id)

#if docs.root.doc != none [
  #eval(docs.root.doc, mode: "markup")
]

#for decl in docs.root.decls [
  #render-decl(decl)
]
