#:schema ../schemas/docent.schema.json

[fmt]
include = ["lib/", "internal/", "cmd/"]
sort_imports = true
single_line_braces = false
logical_blank_lines = false
trailing_comma = true

[doc]
invalid_leading_phrase = "allow"
missing_summary_terminal_punctuation = "allow"

[doc.missing_doc_comment]
level = "warn"
check_errors = false
check_parameters = false
check_fields = false
check_enumerators = false
