#:schema ../schemas/docent.schema.json

[style]
scan_mode = "all"

[style.identifier_case]
level = "deny"
functions = "snake_case"
allow_snake_case_struct_files = true

[style.line_length_limit]
level = "forbid"
max_length = 100
