#:schema ../schemas/docent.schema.json

[style]
scan_mode = "all"

[style.identifier_case]
level = "deny"
functions = "snake_case"
struct_file_case = "snake_case"

[style.line_length_limit]
level = "forbid"
max_length = 100
